### ISSUE TITLE
Can't not use

### ISSUE THREAD

**Issue by carpcai** [eledwinn/vue-editable-grid#16]
Why can't I open the page when I follow the readme, it says: document is not defined

**Comment by carpcai** [comment]
Do you have any demo here?

**Comment by eledwinn** [comment]
Let me publish a demo for you.

**Comment by eledwinn** [comment]
You can find a example in this file: https://github.com/eledwinn/vue-editable-grid/blob/master/src/App.vue

You can even clone and run this repository to see it in action.
```
git clone https://github.com/eledwinn/vue-editable-grid.git
cd vue-editable-grid
npm install
npm run serve
```
Let me know if it could solve your problem, if not, please give more details of your code.

**Comment by eledwinn** [comment]
Hi @carpcai, tell me if you install the package in your project, so we can close this issue.

**Comment by szabozoltan69** [comment]
(You could close this. :-)  )

**Comment by carpcai** [comment]
@eledwinn Thanks, I've solved my problem
