### ISSUE TITLE
Typing a date with numbers gives longer years

### ISSUE THREAD

**Issue by szabozoltan69** [eledwinn/vue-editable-grid#20]
Dear Edwin,

 if we type a date (in a date field, format: "yyyy-MM-dd"), and we use only numbers, then the year gets 5 or 6 digits long.
![image](https://user-images.githubusercontent.com/6050643/98842762-53f9ed00-244a-11eb-9e42-8591ad21cb03.png)

Is it possible to limit it to 4?

**Comment by eledwinn** [comment]
Hi @szabozoltan69 , we are using. `<input type='date' />` element, we are limited to what this control can do. Do you know if we can do that in this element?

**Comment by Otisz** [comment]
The date input tag has same attribututes like the number input: min, max, step
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Additional_attributes

A column def already can handle format:
`{ ...,  format: 'MMM dd, yyyy', ... },`
If `max` property is undefined, the default value can be 9999-12-31. Same logic with `min` property.

In my opinion this is a simple solution.

**Comment by eledwinn** [comment]
Great, that's fine with me. I will be working on this this week.
Or if you prefer, feel free to send your PullRequest 😄

**Comment by szabozoltan69** [comment]
Thanks for the enhancement! Great work!

**Comment by eledwinn** [comment]
Published as version 0.3.17 🚀
