### ISSUE TITLE
Bold indicator of mandatory columns

### ISSUE THREAD

**Issue by szabozoltan69** [eledwinn/vue-editable-grid#21]
Dear Edwin,

 I would like to have a possibility to emphasize some of the header names (to show that they are mandatory).
For example, an * at the end of the header name would be good. This way (or some better way) in VueEditableGrid.vue:

            span.header-content(v-if="column.headerName.substring(column.headerName.length - 1) == '*'") <b>{{ column.headerName.substring(0, column.headerName.length - 1) }}</b>
            span.header-content(v-else) {{ column.headerName }}

Do you think it would make sense?
(And also an italics possibility would be fine, e.g. via § ending.)

To have more rich feedback to the users, some tooltip possibility also would be fine.
I tried it, but could not point to cells one-by-one – I could only point to the whole table, via:
$('.grid-table tbody').attr("data-toggle", "tooltip").attr("title", "Help text")
Or, some header field can be selected also:
$('th.sortable:nth-child(3)').attr("data-toggle", "tooltip").attr("title", You are here');
But the real cells could not be selected. Maybe due to mouse override?

(Workaround for bold headers: this way also css can be applied, e.g. appending: .css('font-weight', 'bold')

**Comment by eledwinn** [comment]
Hi @szabozoltan69 , I think we could enable using custom css in headers.

**Comment by szabozoltan69** [comment]
That's correct - corresponding to the header bolding.

But the "tooltip to cell fields" should be somehow fine. I could not do it even via css either.

**Comment by eledwinn** [comment]
> But the "tooltip to cell fields" should be somehow fine. I could not do it even via css either.

@szabozoltan69 please create new Issue to review this feature.

**Comment by szabozoltan69** [comment]
Great enhancement, this column classname!

**Comment by eledwinn** [comment]
Published as version 0.3.17 🚀
