### ISSUE TITLE
cannot change the min-height of the table displayed 

### ISSUE THREAD

**Issue by anthonychen118** [eledwinn/vue-editable-grid#28]
Using the example data provided, the table will always show all rows, which makes the entire page too long. I was trying to modify the "min-height" of the table but no matter what changes I made to ```node_modules\vue-editable-grid\src\components\VueEditableGrid.vue``` nothing has changed on the webpage. It always shows a min-height of 5610px (number of rows 187 * default height of each row 30px). Even I change the default height of each row, the table still stays the same.  

![image](https://user-images.githubusercontent.com/23109301/103329683-b5821500-4a12-11eb-9258-86c54c81736e.png)

What should I do if I need to modify the "height" of the table?  

BTW, I am using npm to install the module, quasar for localhost live show

**Comment by eledwinn** [comment]
Hi @anthonychen118, should work setting height to vue-editable-grid component. Check this sandbox example:
https://codesandbox.io/s/demo-vue-editable-grid-thuof
Let me know if this problem is solved.

**Comment by anthonychen118** [comment]
Hi @eledwinn , after several trials, it looks like it is not the package's issue but my lack of knowledge in npm. As I said, simply editing ```node_modules\vue-editable-grid\src\components\VueEditableGrid.vue``` will have no effect on my localhost live show, but when I edit the ```node_modules\vue-editable-grid\dist\VueEditableGrid.common.js```, corresponding change will be reflected on the website. I assume this is just how npm works? Since the js file is compiled by Vue and not hand-writtien, it would be more convenient if I can directly edit the .vue file for customization. Are you aware of anyway to do that?

**Comment by eledwinn** [comment]
Hi @anthonychen118 , Ideally, you don't have to edit any files within the vue-editable-grid package, because when we do an update your code could be replaced. Try to make the customizations from your own code, if it is not possible, then request the functionalities you need through a new Github Issue, or send us a PullRequest with the improvement you want so that it can be reviewed.
