### ISSUE TITLE
sub objetc selector

### ISSUE THREAD

**Issue by joselopez85** [eledwinn/vue-editable-grid#35]
Ex: 
myObje = [
{ name: 'kel', phone: '7589658478', 
  aspects:  { hair: 'short', skin: 'white' }, // <---- show this in table ??
  address: 'none'
}
How show subojects on table? thanks!
beacuse:
{ headerName: 'Skin', field: 'aspects.skin' } no work

**Comment by joselopez85** [comment]
Work fine:

{
  headerName: 'Skin',
  field: 'aspects',
  formatter: (event) => {
    return `${event.row.spaects.skin}`
  }
}

**Comment by joselopez85** [comment]
Now, exists any way insert HTML into cell?? Sorry for my english

**Comment by eledwinn** [comment]
Hi @joselopez85 , I was bussy with another proyects last year, but I really aprecate your comments about this library.
Unfortunately there isn't a way to inject HTML.
I'm going to close this thread, but if you have another Issue or suggestion please feel free to add another ticket.
